resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Esta aplicação tem como objetivo mostrar o uso dos motores de
      inteligência artificial em uma aplicação de Estação de Tratamento de
      Efluentes, fornecendo ao usuário a possibilidade de monitoramento remoto
      das variáveis dos processos para controle de pH, além da aplicação de
      algoritmos matemáticos para encontrar a melhor sintonia e performance para
      a sua malha de controle, e uso de algoritmos de Inteligencia Artificial
      para melhor entendimento e previsão, do comportamento de algumas variáveis
      presente, visando a otimização do processo.
    filesPath: ./files
    globals:
      - cloudOnly: false
        description: Aqui deve ser inserido no campo Value o username obtido.
        json: '"USERNAME"'
        key: user
      - cloudOnly: false
        description: Aqui deve ser inserido no campo Value o password obtido.
        json: '"PASSWORD"'
        key: pass
      - cloudOnly: false
        description: Aqui deve ser inserido no campo Value o Id do Projeto obtido.
        json: "0"
        key: idProjeto
      - cloudOnly: false
        description: Aqui deve ser inserido no campo Value o token API gerado.
        json: '"TOKEN API"'
        key: tokAPI
    id: ~exportplaceholderid-application-applicationBirminDEstacaoDeTratamentoDeEfluentes-0~
    name: BirminD - Estação de Tratamento de Efluentes
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords: []
version: 1
