resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Dynamic provisioning of devices for Experience Users or Experience Groups.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryDevicesProvisioningDynamicProvisioning~
    name: Dynamic Provisioning
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - device
version: 1
