resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Adds the Google Analytics tracking code to your application experience.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsGoogleAnalytics~
    name: Google Analytics
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
