resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Allow Experience Users to change their passwords.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesFormsChangeUserPassword~
    name: Change User Password
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - featured
      - password
      - ui
      - user
version: 1
