resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Provides a reference implementation for a paginated table of devices.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesPagesPaginatedDeviceTable~
    name: Paginated Device Table
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
