resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example demonstrates how to use the registered function compress_file.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedFeaturesCompressFile~
    name: Features Compress File
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
