resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Redacts a payload, obscuring sensitive values based on property names.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesRedactPayload~
    name: Redact Payload
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - node
version: 1
