resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Calculates a moving average over a configurable number of data points.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesMovingAverage~
    name: Moving Average
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
