resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Converts temperatures between Celsius, Fahrenheit, and Kelvin.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesConvertTemperature~
    name: Convert Temperature
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
