resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example demonstrates how to use the functions related to I/O events.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedApplicationsIosEvents~
    name: Ios Events
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
