resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Provides the ability for experience users to reset a forgotten password.
    filesPath: ./files
    globals:
      - cloudOnly: true
        json: '"YOUR_RESET_TOKEN_SECRET"'
        key: tl-jwt-reset-secret
      - cloudOnly: true
        json: '"example.com"'
        key: tl-jwt-reset-issuer
    id: ~exportplaceholderid-application-libraryExperiencesFormsForgotPassword~
    name: Forgot Password
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
