resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Includes implementations for 404 and 500 error pages.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesPagesUserFriendlyErrorPages~
    name: User-Friendly Error Pages
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
