resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Renders a QR code scanner and processes the data within a scanned code.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsQrCodeReader~
    name: QR Code Reader
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - qr
      - code
version: 1
