resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Allows for setting agent configuration files via a local web interface.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEdgeComputeEdgeAgentConfigurationPage~
    name: Edge Agent Configuration Page
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
