resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example demonstrates how to use the API related to LED control and monitoring.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedApplicationsLedsLedsConfig~
    name: Leds Config
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
