resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node provides the ability to report a SIGNL4 event via the SIGNL4 API.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesSignl4Alert~
    name: SIGNL4 Alert
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
