resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: "- Adjust README overview"
    filesPath: ./files
    globals:
      - cloudOnly: true
        json: "{\r

          \    \"microsoft\": {\r

          \        \"clientId\":
          \"bf943089-da3a-42b1-b313-87873bbeb130\",\r

          \        \"clientSecret\":
          \"_0c8Q~KPwlHxWt4wuz2VBSY6sUMApBInIZiz_cp5\"\r

          \    }\r

          }"
        key: oauth
      - cloudOnly: false
        json: '"azureadoauthtest.~exportplaceholderid-endpoint-domain~"'
        key: hostname
    id: ~exportplaceholderid-application-libraryExperiencesFormsAzureAdOauthWeg-0~
    name: AzureAD Oauth WEG
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - oauth
      - authentication
      - google
version: 1
