resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Immediately send a web push message using the Braze API.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesBrazeWebPush~
    name: Braze Web Push
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - node
version: 1
