resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Log payload data to Loggly using their HTTP API.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesLoggly~
    name: Loggly
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
