resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Monitors real-time geolocation, temperature, and shock for multiple
      asset tracking devices.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-applicationAssetTracker~
    name: Asset Tracker
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
