resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This template demonstrates the use of an on-disk workflow to enable
      an Edge Agent to register itself as a new device.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEdgeComputeEdgeAgentAutoRegistration~
    name: Edge Agent Auto Registration
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
