resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This template demonstrates how to authenticate to an Experience
      using Single Sign-On (SSO) with Azure Active Directory.
    filesPath: ./files
    globals:
      - cloudOnly: true
        json: '"identityProviderMetadataTemplate"'
        key: identityProviderMetadataTemplate_example_com
      - cloudOnly: true
        json: '"serviceProviderMetadataTemplate"'
        key: serviceProviderMetadataTemplate_example_com
    id: ~exportplaceholderid-application-libraryExperiencesFormsAzureActiveDirectorySso~
    name: Azure Active Directory SSO
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
