resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Allow Experience Users to update their profile.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesFormsUserProfile~
    name: User Profile
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - ui
      - user
version: 1
