resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: A general-purpose pagination UI component.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsPaginator~
    name: Paginator
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - ui
      - paginator
version: 1
