resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node generates OAuth Tokens from Google Cloud Service Accounts.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesGcpOAuth~
    name: GCP OAuth
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - node
version: 1
