resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This template reduces wasted time searching for huddle rooms by
      providing a real-time space availability and utilization application.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-applicationHuddleRoomMonitor~
    name: Huddle Room Monitor
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
