resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Demonstrates how to use a form to receive user input and process
      that input using a workflow.
    filesPath: ./files
    globals:
      - cloudOnly: false
        json: '"featured"'
        key: template-kewords
    id: ~exportplaceholderid-application-libraryExperiencesFormsBasicInputForm~
    name: Basic Input Form
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
