resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Demonstrates how to upload a file from an edge compute device to
      Application Files.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEdgeComputeUploadToApplicationFiles~
    name: Upload to Application Files
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
