resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example shows how to calculate the MD5 hash of a string.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedFeaturesMd5~
    name: Features Md5
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
