resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: "Displays a list of devices. Each entry has a configurable link,
      label, and optional device image. "
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsDeviceList~
    name: Device List
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - featured
version: 1
