resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example demonstrates how to use the functions related to I/O manipulations.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedApplicationsIosDataManipulation~
    name: Ios Data Manipulation
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
