resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Downsamples (or decimates) buckets of data points into a single value.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesDownsample~
    name: Downsample
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - node
version: 1
