resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Demonstrates how to use Auth0 as a third-party login provider for
      your Experience Users.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesFormsAuth0SocialLogin~
    name: Auth0 Social Login
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
