resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Calculates the distance, in meters, between two GPS coordinates.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesGpsDistance~
    name: GPS Distance
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
