resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node provides access to the Google Vision API.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesGcpVisionApi~
    name: GCP Vision API
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
