resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example demonstrates how to use the functions related to directories such as - create_dir, read_dir, and dir_size.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedFeaturesDir~
    name: Features Dir
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
