resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: >-
      Template responsible for ensuring the creation of the measurements table
      during device initialization or reconnection.
    filesPath: ./files
    globals:
      - cloudOnly: false
        json: '"edge,table"'
        key: template-keywords
    id: ~exportplaceholderid-application-libraryWorkflowsEdgeComputeCreateTable~
    name: Create Measurements Table
    privateFilesPath: ./privateFiles
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
