resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: O módulo EXPERIENCE é o meio pelo qual pode-se construir uma
      interface web para usuários interagirem com o que foi desenvolvido na
      plataforma. Esse módulo fornece algumas ferramentas que foram utilizadas
      nesse modelo para entregar uma aplicação de controle de usuários com
      sistema de login, cadastro e exclusão de contas, permissões por grupos de
      usuários, navegação entre páginas e muito mais.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-applicationModuloExperienceUsersAndGroups-0~
    name: Módulo EXPERIENCE (Users and Groups)
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords: []
version: 1
