resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: >-
      Template responsible for reading measurements from an Edge Compute device
      every 30 seconds.
    filesPath: ./files
    globals:
      - cloudOnly: false
        json: '"edge,read"'
        key: template-keywords
    id: >-
      ~exportplaceholderid-application-libraryWorkflowsEdgeComputeReadMeasurements~
    name: Library / Workflows / Edge Compute / Read Measurements
    privateFilesPath: ./privateFiles
    readmePath: ./README.md
version: 1
