resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Demonstrates how to send JS scripts and JSON to your edge agent for
      use within the Function Node.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEdgeComputeFunctionNodeScripts~
    name: Function Node Scripts
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
