resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example shows how to perform configurations, additions, and removals of devices through requests.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedApplicationsModbusRemoteConfig~
    name: Modbus Remote Config
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
