resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Fetches random images, saves them to device state, and renders them
      on dashboards.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsSimulatorsBlobSimulator~
    name: Blob Simulator
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
