resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: >-
      Prebuilt and production-ready template that significantly reduces the
      development time and complexity for your applications.
    filesPath: ./files
    globals:
      - cloudOnly: true
        json: '"a super secret value"'
        key: cpf-jwt-password-reset-secret
    id: >-
      ~exportplaceholderid-application-applicationWeGnologyConnectedProductFoundation~
    name: Application / WEGnology Connected Product Foundation
    readmePath: ./README.md
version: 1
