resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Demonstrates usage of the Latch Node, and auto-creating and
      auto-resolving events.
    filesPath: ./files
    globals:
      - cloudOnly: false
        json: '"featured"'
        key: template-kewords
    id: ~exportplaceholderid-application-libraryWorkflowsAlertingLatchingAndEvents~
    name: Latching and Events
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
