resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node provide access to Hologram's API to retrieve device information.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesHologramGetDevice~
    name: Hologram Get Device
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - node
version: 1
