resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: OEE calculations and dashboards for simulated paper machines.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-applicationOverallEquipmentEffectiveness~
    name: Overall Equipment Effectiveness
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
