resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This template includes an Experience Endpoint to authenticate and
      return an authentication token for Experiences Users via a RESTful API.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesApIsAuthenticationEndpoint~
    name: Authentication Endpoint
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - api
version: 1
