resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Simulates a GPS device traveling along a predefined route.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsSimulatorsOutdoorAssetTracker~
    name: Outdoor Asset Tracker
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
