resourceType: Flow
resources:
  - description: >-
      Esse exemplo mostra como realizar a manipulação de dados de um dispositivo
      e também como obter o status de todos os dispositivos.
    exportHash: 7a092bf81248e25d2ea5c3cc465d1d8be3383f1b74227b650d60ee3a5798001e
    flowClass: embedded
    globals: []
    id: >-
      ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~
    minimumAgentVersion: 0.0.0
    name: edge-wegnology-templates\embedded\applications\modbus\data_manipulation
    nodes:
      - config: {}
        id: _jEoxoYvt2
        meta:
          annotationText: Inicializa se inscrevendo no tópico da escuta das respostas
          category: annotation
          height: 120
          label: Note
          name: note
          width: 220
          x: 40
          'y': 20
        outputIds: []
        type: AnnotationNode
      - config:
          messageTemplate: '{{data}}'
          resultPath: ''
          topicTemplate: modbus-api/v1/read
        id: eW_lA9RD9q
        meta:
          category: output
          description: ''
          label: Read
          name: mqtt
          x: 880
          'y': 380
        outputIds:
          - - I9PDzxBA4b
        type: MqttMessageNode
      - config:
          level: verbose
          message: ''
          property: ''
        id: I9PDzxBA4b
        meta:
          category: debug
          description: ''
          label: Debug
          name: debug
          x: 880
          'y': 480
        outputIds: []
        type: DebugNode
      - config:
          messageTemplate: '{ "topic": "modbus-api/v1/read/response" }'
          resultPath: ''
          topicTemplate: eea-api/v1/subscribe
        id: dhZaBwFtsL
        meta:
          category: output
          description: ''
          label: MQTT
          name: mqtt
          x: 60
          'y': 260
        outputIds:
          - - ZR0ZAznhFO
        type: MqttMessageNode
      - config:
          destination: data
          errorBehavior: throw
          errorPath: ''
          source: data
        id: PTzFw_3RFB
        meta:
          category: logic
          description: ''
          label: 'JSON: Decode'
          name: json-decode
          x: 1180
          'y': 380
        outputIds:
          - - rQrHVNN3zY
        type: JsonDecodeNode
      - config:
          level: verbose
          message: ''
          property: ''
        id: rQrHVNN3zY
        meta:
          category: debug
          description: ''
          label: Debug
          name: debug
          x: 1180
          'y': 480
        outputIds: []
        type: DebugNode
      - config:
          messageTemplate: '{{data}}'
          resultPath: ''
          topicTemplate: modbus-api/v1/peripherals/add
        id: KpXM_x6ZYW
        meta:
          category: output
          description: ''
          label: Peripherals Add
          name: mqtt
          x: 580
          'y': 380
        outputIds:
          - - 87iPgAaj_a
        type: MqttMessageNode
      - config:
          level: verbose
          message: ''
          property: ''
        id: 87iPgAaj_a
        meta:
          category: debug
          description: ''
          label: Debug
          name: debug
          x: 580
          'y': 480
        outputIds: []
        type: DebugNode
      - config: {}
        id: p1cEUidlQO
        meta:
          annotationText: >-
            Cria um novo dispositivo para a execução do exemplo.


            - **payload** => Arquivo em JSON contendo todas as informações do
            dispositivo.
          category: annotation
          height: 160
          label: Note
          name: note
          width: 260
          x: 540
          'y': 80
        outputIds: []
        type: AnnotationNode
      - config:
          messageTemplate: '{ "topic": "modbus-api/v1/write/response" }'
          resultPath: ''
          topicTemplate: eea-api/v1/subscribe
        id: ZR0ZAznhFO
        meta:
          category: output
          description: ''
          label: MQTT
          name: mqtt
          x: 60
          'y': 360
        outputIds:
          - - 9l1Ybvh39g
        type: MqttMessageNode
      - config:
          messageTemplate: '{{data}}'
          resultPath: ''
          topicTemplate: modbus-api/v1/write
        id: Suy2tUTECo
        meta:
          category: output
          description: ''
          label: Write
          name: mqtt
          x: 580
          'y': 920
        outputIds:
          - - Q_dfyhYl7Y
        type: MqttMessageNode
      - config:
          level: verbose
          message: ''
          property: ''
        id: Q_dfyhYl7Y
        meta:
          category: debug
          description: ''
          label: Debug
          name: debug
          x: 580
          'y': 1020
        outputIds: []
        type: DebugNode
      - config:
          destination: data
          errorBehavior: throw
          errorPath: ''
          source: data
        id: tz5lKRH9Bi
        meta:
          category: logic
          description: ''
          label: 'JSON: Decode'
          name: json-decode
          x: 880
          'y': 920
        outputIds:
          - - Egv9bASLZO
        type: JsonDecodeNode
      - config:
          level: verbose
          message: ''
          property: ''
        id: Egv9bASLZO
        meta:
          category: debug
          description: ''
          label: Debug
          name: debug
          x: 880
          'y': 1020
        outputIds: []
        type: DebugNode
      - config:
          messageTemplate: '{ "topic": "modbus-api/v1/status/response" }'
          resultPath: ''
          topicTemplate: eea-api/v1/subscribe
        id: 9l1Ybvh39g
        meta:
          category: output
          description: ''
          label: MQTT
          name: mqtt
          x: 60
          'y': 460
        outputIds: []
        type: MqttMessageNode
      - config:
          messageTemplate: '{}'
          resultPath: ''
          topicTemplate: modbus-api/v1/status
        id: Dk6BfpsMDv
        meta:
          category: output
          description: ''
          label: Status
          name: mqtt
          x: 1160
          'y': 920
        outputIds:
          - - _YQ_2bTK6E
        type: MqttMessageNode
      - config:
          level: verbose
          message: ''
          property: ''
        id: _YQ_2bTK6E
        meta:
          category: debug
          description: ''
          label: Debug
          name: debug
          x: 1160
          'y': 1020
        outputIds: []
        type: DebugNode
      - config:
          destination: data
          errorBehavior: throw
          errorPath: ''
          source: data
        id: w7R0KwiRGR
        meta:
          category: logic
          description: ''
          label: 'JSON: Decode'
          name: json-decode
          x: 1420
          'y': 920
        outputIds:
          - - 2llO75FjlD
        type: JsonDecodeNode
      - config:
          level: verbose
          message: ''
          property: ''
        id: 2llO75FjlD
        meta:
          category: debug
          description: ''
          label: Debug
          name: debug
          x: 1420
          'y': 1020
        outputIds: []
        type: DebugNode
      - config: {}
        id: TPlkm6OgDV
        meta:
          annotationText: >-
            Faz uma requisição de leitura das informações do dispositivo
            recém-criado.


            - **payload** => Arquivo em JSON contendo as informações
            requisitadas, assim como a conexão e id do dispositivo.
          category: annotation
          height: 200
          label: Note
          name: note
          width: 260
          x: 840
          'y': 40
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: mA6aCVVFkg
        meta:
          annotationText: Resposta da requisição da leitura.
          category: annotation
          height: 100
          label: Note
          name: note
          width: 140
          x: 260
          'y': 240
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: eQS7yZscVd
        meta:
          annotationText: Resposta da requisição de escrita.
          category: annotation
          height: 100
          label: Note
          name: note
          width: 140
          x: 260
          'y': 340
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: Bzd7aUI3Mb
        meta:
          annotationText: Resposta da requisição do status.
          category: annotation
          height: 100
          label: Note
          name: note
          width: 140
          x: 260
          'y': 440
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: AMyj5Q6x3f
        meta:
          annotationText: |-
            Escuta a requisição de leitura do dispositivo.

            - **data.data.message** => Contém o resultado da operação
          category: annotation
          height: 160
          label: Note
          name: note
          width: 260
          x: 1140
          'y': 80
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: nUi7DXzlO_
        meta:
          annotationText: >-
            **Principais informações.**

            ****

            - **protocol** => Tipo de comunicação com o Gateway RTC ou TCP.

            - **unit_id** => Id serial da porta serial

            - **timeout** => Tempo máximo de operação.

            - **instructions** => Objeto contendo as instruções para determinar
            o que será requisitado.
          category: annotation
          height: 240
          label: Note
          name: note
          width: 360
          x: 1740
          'y': 200
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: PdOdL7D5EG
        meta:
          annotationText: >
            **Atributos do "instructions".**

            ****

            - **function** => Função do comando modbus Ex.: “coil” ou "di” ou
            “ir” ou “hr”.

            - **adress** => Endereço do primeiro registrador do grupo de

            registradores na sequência.

            - **size** => Quantidade de registradores no grupo.

            - **registers** => Objeto contendo o conjunto de informações de

            resposta do registrador.
          category: annotation
          height: 240
          label: Note
          name: note
          width: 360
          x: 1740
          'y': 460
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: L7hTq2bvk6
        meta:
          annotationText: >-
            **Atributos do "registers".**

            ****

            - **name** => Nome do registrador.

            - **datatype** => Descrição do tipo de dado do registrador, Ex:
            "U16", "I16", etc.

            - **scale** => Escala do registrador.

            - **on_change** => Indica se o on change está habilitado.
          category: annotation
          height: 220
          label: Note
          name: note
          width: 360
          x: 1740
          'y': 720
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: CRdXdR7Oua
        meta:
          annotationText: >-
            Faz uma escrita nos valores do dispositivo através do modbus


            - **payload** => Arquivo em JSON contendo as informações
            requisitadas.

            - **value** => Valor que será escrito na função.
          category: annotation
          height: 200
          label: Note
          name: note
          width: 280
          x: 540
          'y': 580
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: Y8UVawzf9T
        meta:
          annotationText: |-
            Escuta a requisição de escrita do dispositivo

            - **data.data.message** => Contém o resultado da operação
          category: annotation
          height: 160
          label: Note
          name: note
          width: 260
          x: 840
          'y': 620
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: 5uZzPgKovu
        meta:
          annotationText: Faz uma requisição do status de todos os dispositivos conectados.
          category: annotation
          height: 100
          label: Note
          name: note
          width: 220
          x: 1140
          'y': 680
        outputIds: []
        type: AnnotationNode
      - config: {}
        id: vwq9vqer4N
        meta:
          annotationText: |-
            Escuta a requisição de status do dispositivo.

            - **data.data.message** => Contém o resultado do status.
          category: annotation
          height: 160
          label: Note
          name: note
          width: 220
          x: 1400
          'y': 620
        outputIds: []
        type: AnnotationNode
    triggers:
      - config: {}
        key: 2le6mC3ytj3Ci4kL993Tm
        meta:
          category: trigger
          description: ''
          label: 'EEA: Init'
          name: eeaInit
          uiId: J0uOTJcmAH
          x: 60
          'y': 160
        outputIds:
          - - dhZaBwFtsL
        type: onBoot
      - config: {}
        key: >-
          ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~-p4wG3bS05O3ieyocb6Gh9
        meta:
          category: trigger
          description: ''
          label: Virtual Button
          name: virtualButton
          payload: "{\r\n\"protocol\": {\r\n    \"modbusTcp\": {\r\n      \"host\": \"192.168.2.11:502\"\r\n    }\r\n  },\r\n\"unit_id\": 20,\r\n\"timeout\": 500,\r\n\"instructions\":[\r\n{\r\n  \"function\": \"ir\",\r\n  \"address\": 9000,\r\n  \"size\": 3,\r\n  \"registers\": [\r\n    {\r\n    \"name\": \"IR0ETH\",\r\n    \"datatype\": \"u16\",\r\n    \"scale\": 1.0,\r\n    \"on_change\": 0.0\r\n    },\r\n    {\r\n    \"name\": \"IR1ETH\",\r\n    \"datatype\": \"u16\",\r\n    \"scale\": 1.0\r\n    },\r\n    {\r\n    \"name\": \"IR1ETH\",\r\n    \"datatype\": \"u16\",\r\n    \"scale\": 1.0\r\n    }\r\n  ]\r\n}\r\n]\r\n}\r\n"
          uiId: >-
            ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~-p4wG3bS05O3ieyocb6Gh9
          x: 880
          'y': 280
        outputIds:
          - - eW_lA9RD9q
        type: virtualButton
      - config: {}
        key: modbus-api/v1/read/response
        meta:
          category: trigger
          description: ''
          label: Read Response
          name: mqtt
          uiId: Qs_cU3RN3D
          x: 1180
          'y': 280
        outputIds:
          - - PTzFw_3RFB
        type: mqttTopic
      - config: {}
        key: >-
          ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~-zOlaI3e6peli1U2BUbZjB
        meta:
          category: trigger
          description: ''
          label: Virtual Button
          name: virtualButton
          payload: "[\r\n{\r\n  \"name\": \"API_Test\",\r\n  \"id\": \"\",\r\n  \"protocol\": {\r\n    \"modbusTcp\": {\r\n      \"host\": \"192.168.2.11:502\"\r\n    }\r\n  },\r\n  \"registers\": [\r\n    {\r\n      \"address\": 9000,\r\n      \"function\": \"ir\",\r\n      \"name\": \"IR0ETH\",\r\n      \"dtype\": \"u16\",\r\n      \"scale\": 1,\r\n      \"events\": {\r\n        \"on_change\": 0.0\r\n      },\r\n      \"information\": {\r\n        \"max\": true,\r\n        \"min\": true,\r\n        \"avg\": true,\r\n        \"last\": true,\r\n        \"diff\": true\r\n      }\r\n    },\r\n    {\r\n      \"address\": 9001,\r\n      \"function\": \"ir\",\r\n      \"name\": \"IR1ETH\",\r\n      \"dtype\": \"u16\",\r\n      \"scale\": 1,\r\n      \"events\": {\r\n        \"alarms\": {\r\n          \"hys\": 1.0,\r\n          \"high\": 100.0,\r\n          \"low\": 20.0\r\n        }\r\n      },\r\n      \"information\": {\r\n        \"max\": false,\r\n        \"min\": false,\r\n        \"avg\": true,\r\n        \"last\": true,\r\n        \"diff\": false\r\n      }\r\n    },\r\n    {\r\n      \"address\": 900,\r\n      \"function\": \"ir\",\r\n      \"name\": \"IR1ETH\",\r\n      \"dtype\": \"u16\",\r\n      \"scale\": 1,\r\n      \"information\": {\r\n        \"max\": true,\r\n        \"min\": true,\r\n        \"avg\": true,\r\n        \"last\": false,\r\n        \"diff\": false\r\n      }\r\n    }\r\n  ],\r\n  \"endianess\": \"big\",\r\n  \"unitId\": 20\r\n}\r\n]"
          uiId: >-
            ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~-zOlaI3e6peli1U2BUbZjB
          x: 580
          'y': 280
        outputIds:
          - - KpXM_x6ZYW
        type: virtualButton
      - config: {}
        key: >-
          ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~-CqX9kLFINaY2ojfXu8ok0
        meta:
          category: trigger
          description: ''
          label: Virtual Button
          name: virtualButton
          payload: "{\r\n\"protocol\": {\r\n    \"modbusTcp\": {\r\n      \"host\": \"192.168.2.11:502\"\r\n    }\r\n  },\r\n\"unit_id\": 20,\r\n\"timeout\": 5000,\r\n\"instructions\":\r\n  [\r\n    {\r\n    \"function\": \"hr\",\r\n    \"address\": 1000,\r\n    \"size\": 3,\r\n    \"values\": [10, 20, 30]\r\n    }\r\n  ]\r\n}\r\n"
          uiId: >-
            ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~-CqX9kLFINaY2ojfXu8ok0
          x: 580
          'y': 820
        outputIds:
          - - Suy2tUTECo
        type: virtualButton
      - config: {}
        key: modbus-api/v1/write/response
        meta:
          category: trigger
          description: ''
          label: Write Response
          name: mqtt
          uiId: jH0be4Q9nU
          x: 880
          'y': 820
        outputIds:
          - - tz5lKRH9Bi
        type: mqttTopic
      - config: {}
        key: >-
          ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~-F05qsZQjS8Yikl9jchysA
        meta:
          category: trigger
          description: ''
          label: Virtual Button
          name: virtualButton
          payload: ''
          uiId: >-
            ~exportplaceholderid-flow-edgeWegnologyTemplatesEmbeddedApplicationsModbusDataManipulation~-F05qsZQjS8Yikl9jchysA
          x: 1160
          'y': 820
        outputIds:
          - - Dk6BfpsMDv
        type: virtualButton
      - config: {}
        key: modbus-api/v1/status/response
        meta:
          category: trigger
          description: ''
          label: Status Response
          name: mqtt
          uiId: 7SEdJsPTGF
          x: 1420
          'y': 820
        outputIds:
          - - w7R0KwiRGR
        type: mqttTopic
version: 1
