resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This workflow monitors and stores the count of connection/disconnection events between the device and the platform. The connection and disconnection events are captured through the Direct Trigger.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedFeaturesDirectTrigger~
    name: Features Direct Trigger
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
