resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Display values of device tags and allow experience users to edit them.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesPagesEditDeviceTags~
    name: Edit Device Tags
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
