resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example demonstrates how to use the API related to the system.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedApplicationsSysStatusManagement~
    name: Sys Status Management
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
