resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Displays a collapsible list of nested items as checkboxes or links.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsCollapsibleTree~
    name: Collapsible Tree
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - ui
      - tree
version: 1
