resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Demonstrates how to build a multilingual Application Experience.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesPagesInternationalization~
    name: Internationalization
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
