resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node provide access to Particle's Remote Diagnostics API to
      retrieve device information.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesParticleDiagnostics~
    name: Particle Diagnostics
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
