resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: An Experience User login form with authentication workflow.
    filesPath: ./files
    globals:
      - cloudOnly: false
        json: '"featured,ui,login,auth,user"'
        key: template-kewords
    id: ~exportplaceholderid-application-libraryExperiencesFormsLogIn~
    name: Log In
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
