resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Demonstrates how to upload an Experience User's file to Application Files.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesFormsFileUpload~
    name: File Upload
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - featured
      - upload
      - files
      - ui
version: 1
