resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Template that makes it easy to add the WEG logo into custom experiences.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsWegLogo-0~
    name: WEG Logo
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - weg
      - logo
      - img
      - image
      - featured
version: 1
