resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This template is an example implementation of SMS-based two-factor
      authentication using Twilio Verify.
    filesPath: ./files
    globals:
      - cloudOnly: false
        json: '"YOUR_SID"'
        key: TWILIO_ACCOUNT_SID
      - cloudOnly: false
        json: '"YOUR_AUTH_TOKEN"'
        key: TWILIO_AUTH_TOKEN
      - cloudOnly: false
        json: '"YOUR_VERIFICATION_SID"'
        key: VERIFICATION_SID
      - cloudOnly: false
        json: '"YOUR_SECRET"'
        key: TL_VERIFY_SECRET
    id: ~exportplaceholderid-application-libraryExperiencesPagesTwilioVerify~
    name: Twilio Verify
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
