resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example shows how to use the Bluetooth functions.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEdgeComputeEmbeddedApplicationsBleCommunicationWithDevices~
    name: Ble Communication With Devices
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
