resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This example demonstrates how to use the functions related to compression and variable transformations.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsEmbeddedFeaturesCompressStringH64~
    name: Features Compress String H64
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
