resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node provides access to Algolia's Search Index HTTPS GET API.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesAlgolia~
    name: Algolia
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
