resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: >-
      Template responsible for aggregating measurements and publishing the
      processed values every 5 minutes.
    filesPath: ./files
    globals: []
    id: >-
      ~exportplaceholderid-application-libraryWorkflowsEdgeComputePublishAggregatedMeasurements~
    name: Publish Aggregated Measurements
    privateFilesPath: ./privateFiles
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - edge
version: 1
