resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Establishes a stream of real-time state reports for a device and
      displays the state values.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsDeviceStateStream~
    name: Device State Stream
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords:
      - device
version: 1
