resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Renders a Google Map with pins, including optional custom markers
      and info bubbles.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsGoogleMaps~
    name: Google Maps
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: WEGnology
    authorUrl: https://docs.app.wnology.io
    keywords: []
version: 1
